name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Change directory
      run: cd "maven_test"
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.24-8/x64

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests with Maven
      run: mvn test
